version: '3'
services:
  uncommon_main:
    container_name: uncommon
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: uncommon
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - uncommon_main:/var/lib/postgresql/data
  uncommon_test:
    container_name: uncommon_test
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: uncommon_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - uncommon_test:/var/lib/postgresql/data

  uncommon_redis:
    image: redis:6.0-alpine
    ports:
      - "6377:6379"

volumes:
  uncommon_main:
  uncommon_test: